### ISSUE TITLE
ERROR - Exception with print_output:

### ISSUE THREAD

**Issue by hasd-daniel** [paregupt/ucs_traffic_monitor#19]
Hi All
When I installed the OVA I encountered a problem
[root@utm-host utm]# cat /var/log/telegraf/ucs_traffic_monitor/ucs_traffic_monitor_ucs_domains_group_1.log | more 
2020-05-12 01:14:00,209 - WARNING - ---------- START (version 0.319)----------
2020-05-12 01:14:00,209 - INFO - Added 10.100.1.31 to domain dict
2020-05-12 01:14:00,209 - INFO - Trying to unpickle connection for 10.100.1.31
2020-05-12 01:14:00,209 - INFO - Found 10.100.1.31 in /usr/local/telegraf/ucs_traffic_monitor_ucs_domains_group_1.pickle
2020-05-12 01:14:00,428 - INFO - Connect and pull stats: executor_list : [['10.100.1.31', 'cli', None], ['10.100.1.31', 'sdk', <ucsmsdk.ucshandle.UcsHandle object at 0x7fd4b4c40a20>]]
2020-05-12 01:14:00,429 - INFO - Trying to set a new cli connection for 10.100.1.31
2020-05-12 01:14:00,430 - INFO - SDK connection for 10.100.1.31. Time:1589271180, Elapsed:60, Refresh:6880
2020-05-12 01:14:00,745 - INFO - Query class_ids for 10.100.1.31
2020-05-12 01:14:02,616 - INFO - Query completed 10.100.1.31
2020-05-12 01:14:05,475 - INFO - Connection type cli UP for 10.100.1.31 in 5.05s
2020-05-12 01:14:05,475 - INFO - CLI pull Starting on 10.100.1.31 FI-['A', 'B']
2020-05-12 01:14:05,475 - INFO - Connect to NX-OS FI-A for 10.100.1.31
2020-05-12 01:14:07,081 - INFO - Connected. Now run commands FI-A 10.100.1.31
2020-05-12 01:14:07,485 - INFO - -- show int pri -- on 10.100.1.31 FI-A
2020-05-12 01:14:07,988 - INFO - Connect to NX-OS FI-B for 10.100.1.31
2020-05-12 01:14:08,894 - INFO - Connected. Now run commands FI-B 10.100.1.31
2020-05-12 01:14:09,397 - INFO - -- show int pri -- on 10.100.1.31 FI-B
2020-05-12 01:14:09,799 - INFO - CLI pull completed on 10.100.1.31 in 4.32s
2020-05-12 01:14:09,800 - INFO - Start parsing SDK stats for 10.100.1.31
2020-05-12 01:14:09,800 - INFO - Parse env_stats for 10.100.1.31
2020-05-12 01:14:09,800 - INFO - Done: Parse env_stats for 10.100.1.31
2020-05-12 01:14:09,800 - INFO - Parse fi_stats for 10.100.1.31
2020-05-12 01:14:09,801 - INFO - Done: Parse fi_stats for 10.100.1.31
2020-05-12 01:14:09,801 - INFO - Parse compute blades for 10.100.1.31
2020-05-12 01:14:09,801 - INFO - Done: Parse compute blades for 10.100.1.31
2020-05-12 01:14:09,801 - INFO - Parse rack units for 10.100.1.31
2020-05-12 01:14:09,801 - INFO - Done: Parse rack units for 10.100.1.31
2020-05-12 01:14:09,801 - INFO - Parse vnic_stats for 10.100.1.31
2020-05-12 01:14:09,803 - INFO - Done: Parse vnic_stats for 10.100.1.31
2020-05-12 01:14:09,803 - INFO - Parse backplane ports stats for 10.100.1.31
2020-05-12 01:14:09,803 - INFO - Done: Parse backplane ports stats for 10.100.1.31
2020-05-12 01:14:09,803 - INFO - parse_raw_cli_stats for 10.100.1.31
2020-05-12 01:14:09,803 - INFO - FI - A
2020-05-12 01:14:09,803 - INFO - Stats type - pfc_stats
2020-05-12 01:14:09,803 - INFO - Parse pause stats for 10.100.1.31
2020-05-12 01:14:09,804 - INFO - Done: Parse pause stats for 10.100.1.31
2020-05-12 01:14:09,804 - INFO - FI - B
2020-05-12 01:14:09,804 - INFO - Stats type - pfc_stats
2020-05-12 01:14:09,804 - INFO - Parse pause stats for 10.100.1.31
2020-05-12 01:14:09,804 - INFO - Done: Parse pause stats for 10.100.1.31
2020-05-12 01:14:09,804 - INFO - Printing output in InfluxDB Line Protocol format
2020-05-12 01:14:09,804 - ERROR - Exception with print_output:
'transport'
Traceback (most recent call last):
  File "/usr/local/telegraf/ucs_traffic_monitor.py", line 2676, in main
    print_output()
  File "/usr/local/telegraf/ucs_traffic_monitor.py", line 2631, in print_output
    print_output_in_influxdb_lp()
  File "/usr/local/telegraf/ucs_traffic_monitor.py", line 2349, in print_output_in_influxdb_lp
    ',transport=' + per_fi_port_dict['transport']
KeyError: 'transport'
2020-05-12 01:14:09,805 - INFO - Pickle sessions for next time in /usr/local/telegraf/ucs_traffic_monitor_ucs_domains_group_1.pickle : {'10.100.1.31': {'sdk': <ucsmsdk.ucshandle.UcsHandle object at 0x7fd4b4c40a20>, 'sdk_time': 1589271180, 'cli': None}}
2020-05-12 01:14:09,805 - INFO -
    |--------------------------------------------|
    |        Response time - 10.100.1.31          |
    |--------------------------------------------|
    | CLI: Login:    5.05 s  | Query:    4.32 s  |
    | SDK: Login:    0.32 s  | Query:    1.87 s  |
    | Total:     9.37 s                          |
    |--------------------------------------------|
    |--------------------------------------------|
    |          Time taken to complete            |
    |--------------------------------------------|
    |                           Input:  0.219 s  |
    | Connection setup and stats pull:  9.372 s  |
    |                         Parsing:  0.004 s  |
    |                          Output:  0.001 s  |
    |------------------------------------------  |
    |                           Total:  9.596 s  |
    |--------------------------------------------|
2020-05-12 01:14:09,805 - WARNING - ---------- END ---------

Seems like a problem with influxdb.
I was check influxdb but can not find anything. 

[root@utm-host utm]# influx
Connected to http://localhost:8086 version 1.7.10
InfluxDB shell version: 1.7.10
> show databases
name: databases
name
----
_internal
telegraf
> use telegraf
Using database telegraf
> show measurements
name: measurements
name
----
cpu
disk
diskio
kernel
mem
net
netstat
processes
swap
system
>

log telegraf:

[root@utm-host utm]# tail -f /var/log/telegraf/telegraf.log
2020-05-12T08:21:07Z I! Tags enabled: host=utm-host
2020-05-12T08:21:07Z I! [agent] Config: Interval:10s, Quiet:false, Hostname:"utm-host", Flush Interval:10s
2020-05-12T08:21:07Z W! [outputs.influxdb] When writing to [http://localhost:8086]: database "telegraf" creation failed: Post http://localhost:8086/query: dial tcp [::1]:8086: connect: connection refused
2020-05-12T08:48:35Z I! [agent] Hang on, flushing any cached metrics before shutdown
2020-05-12T08:48:35Z I! Loaded inputs: cpu kernel mem system exec exec net disk diskio processes swap
2020-05-12T08:48:35Z I! Loaded aggregators:
2020-05-12T08:48:35Z I! Loaded processors:
2020-05-12T08:48:35Z I! Loaded outputs: influxdb
2020-05-12T08:48:35Z I! Tags enabled: host=utm-host
2020-05-12T08:48:35Z I! [agent] Config: Interval:10s, Quiet:false, Hostname:"utm-host", Flush Interval:10s

Does anyone have a similar problem. Please help me. thanks alot

**Comment by hasd-daniel** [comment]
I was fix issue. The same #17 issue

**Comment by paregupt** [comment]
Hi @hasd-daniel 
If this is a ucs-mini, then it must be same as #17. I do not have a ucs-mini in my lab to make this enhancements. Trying to find help from others. Will you be open to give it a try when I have a fix?
