### ISSUE TITLE
VM-FEX throwws errors in parsing dn

### ISSUE THREAD

**Issue by bakins929** [paregupt/ucs_traffic_monitor#23]
UCSM utilizing VM-FEX will throw parsing errors.  VM-FEX used a software module for distributed forwarding functionality (VEM).  I beleive it is no longer supported and found only in older versions of UCSM.
Following are some log excerpts and trace backs results:

=================
```

2020-06-17 13:13:10,862 - DEBUG - In vnic_stats for 192.168.0.100:sys/chassis-1/blade-1/adaptor-1/host-eth-1/vnic-stats
2020-06-17 13:13:10,862 - DEBUG - In vnic_stats for 192.168.0.100:vmm/vm-5004bb09-91fa-adb8-7071-cb6de2c8d80f/nic-42/vnic-stats

2020-06-17 13:13:11,695 - ERROR - parse_vnic_stats:list index out of range
```

```
Traceback (most recent call last):
  File "/usr/local/telegraf/ucs_traffic_monitor.py", line 1925, in parse_raw_sdk_stats
    obj['DcxVc'])
  File "/usr/local/telegraf/ucs_traffic_monitor.py", line 1607, in parse_vnic_stats
    vif_dict = get_vif_dict_from_dn(domain_ip, item.dn)
  File "/usr/local/telegraf/ucs_traffic_monitor.py", line 750, in get_vif_dict_from_dn
    adaptor = ((str)(dn_list[4])).replace('path', 'adaptor')
IndexError: list index out of range
```

Relevant python3 /usr/local/telegraf/ucs_traffic_monitor.py /usr/local/telegraf/ucs_domains_group_1.txt dict -vvv output
```
Managed Object          :   AdaptorVnicStats
--------------
class_id                        :AdaptorVnicStats
bytes_rx                        :1759172341297
bytes_rx_delta                  :1377006
bytes_rx_delta_avg              :1252216
bytes_rx_delta_max              :1887575
bytes_rx_delta_min              :968267
bytes_tx                        :7031515623385
bytes_tx_delta                  :488897
bytes_tx_delta_avg              :1058131
bytes_tx_delta_max              :2269997
bytes_tx_delta_min              :324423
child_action                    :None
dn                              :vmm/vm-5004bb09-91fa-adb8-7071-cb6de2c8d80f/nic-42/vnic-stats
dropped_rx                      :0
dropped_rx_delta                :0
```

**Comment by paregupt** [comment]
Thank you @bakins929 for helping with the triage and coming up with the fix. This is because of the VM-FEX technology which is not very common anymore. As a fix in v0.41, I will skip the vNIC/vHBA based on VM-FEX.
