### ISSUE TITLE
UCS Errors on obj['DcxVc']

### ISSUE THREAD

**Issue by rshields093** [paregupt/ucs_traffic_monitor#43]
Hello,

This is a great solution that we are looking to utilize in our environments. Thank You!!

I recently deployed the OVA solution for UTM and successfully finished the upgrade to 0.4 UTM.

After deploying the latest ucs_traffic_monitor.py I'm getting the following errors in our ucs_traffic_monitor_ucs_domains_group_1.log and 2.log

Traceback (most recent call last):
  File "/usr/local/telegraf/ucs_traffic_monitor.py", line 2073, in parse_raw_sdk_stats
     obj['DcxVc'])
  File "/usr/local/telegraf/ucs_traffic_monitor.py", line 1623, in parse_vnic_stats
    fill_chassis_dict(item, domain_ip)
  File "/usr/local/telegraf/ucs_traffic_monitor.py", line 975, in fill_chassis_dict
    peer_port = peer_slot + '/' + peer_port
UnboundLocalError: local variable 'peer_slot' referenced before assignment

UTM is not tracking any of the data now that is being pulled from the UCS Fi's.   I logged onto the influxdb and noticed that none of the records are being updated. Also Grafana is not reporting the data as well.

We have roughly 20 sets of Fi's all running on Cisco UCS 6332 with firmware of 4.0.4g. 

Any suggestions on how to fix this issues? 

Any additional info needed please let me know.

**Comment by rshields093** [comment]
Just backed up the version 0.4 /usr/local/telegraf/ucs_traffic_monitor.py and reverted back to version 0.3 ucs_traffice_monitor.py.

Restarted all services telegraf,influxdb,grafana. I'm not getting populated metrics for all my Fi's.

Within the  ucs_traffic_monitor_ucs_domains_group_1.log and 2.log files I'm not seeing the DcxVC Error however getting several of the following messages.

Unable to decode peer_dn:, dn:sys/chassis-1/blade-1/adaptor-1/host-eth-1
Unable to decode peer_dn:, dn:sys/chassis-1/blade-1/adaptor-1/host-eth-2
Unable to decode peer_dn:, dn:sys/chassis-1/blade-1/adaptor-1/host-eth-3
...
...

**Comment by paregupt** [comment]
Are you seeing this on all the domains?
If not, is there anything particular about this domain?

Either case, I can help if you can get me the files from the log directory. I need the full file and all of them. Do you have a Cisco rep who can get those to me without putting them in public domain?

**Comment by nveronski** [comment]
Hi Paresh,
There’s nothing special with this domain.
Pair of FI 6248-UP with  8 UCS 5108 AC2 Chassis, 2208XP IOMs and B200-M3,4,5 servers.
No FEX nor C-Series servers

I can get you the files from /var/log/telegraf/ if that’s what you need.

BTW thank you for the fine work you’ve done with the UTM.



Nick Veronski
Professional Services Engineer
E.      nickv@we-ankor.co.il<mailto:nickv@we-ankor.co.il>
O.      +972-3-6076077
M.    +972-54-7008212
W.    www.we-ankor.co.il<http://www.we-ankor.co.il/>

[cid:image001.png@01D5A8DD.06875970.LogoWeAnkor.jpg]

**Comment by rshields093** [comment]
> 
> 
> Just backed up the version 0.4 /usr/local/telegraf/ucs_traffic_monitor.py and reverted back to version 0.3 ucs_traffice_monitor.py.
> 
> Restarted all services telegraf,influxdb,grafana. I'm not getting populated metrics for all my Fi's.
> 
> Within the ucs_traffic_monitor_ucs_domains_group_1.log and 2.log files I'm not seeing the DcxVC Error however getting several of the following messages.
> 
> Unable to decode peer_dn:, dn:sys/chassis-1/blade-1/adaptor-1/host-eth-1
> Unable to decode peer_dn:, dn:sys/chassis-1/blade-1/adaptor-1/host-eth-2
> Unable to decode peer_dn:, dn:sys/chassis-1/blade-1/adaptor-1/host-eth-3
> ...
> ...

Sorry I meant to say 0.3 ucs_traffic_monitor.py is populating metrics for us now...

**Comment by rshields093** [comment]
> 
> 
> Are you seeing this on all the domains?
> If not, is there anything particular about this domain?
> 
> Either case, I can help if you can get me the files from the log directory. I need the full file and all of them. Do you have a Cisco rep who can get those to me without putting them in public domain?

**Comment by rshields093** [comment]
Yes I do have  Cisco rep that I can provide the log info. I will reach out to him and give you the following logs??

telegraf.log
ucs_traffic_monitor_ucs_domains_group_#.log

Do you want me to revert back to 0.4 ucs_traffic_monitor.py and then populate the log files I'm assuming?

**Comment by rshields093** [comment]
Yes I do have Cisco rep that I can provide the log info. I will reach out to him and give you the following logs??

telegraf.log
ucs_traffic_monitor_ucs_domains_group_#.log

Do you want me to revert back to 0.4 ucs_traffic_monitor.py and then populate the log files I'm assuming?

**Comment by rshields093** [comment]
sent log files to our Cisco Rep, he will send to you shortly. Thanks

**Comment by paregupt** [comment]
I have not received any logs.
I am closing this due to inactivity. You are welcome to re-open if the problem still persists. Thank you for using UTM and your feedback.
