### ISSUE TITLE
Missing measurements tables

### ISSUE THREAD

**Issue by ZenHub01** [paregupt/ucs_traffic_monitor#69]
Hi, 
I installed the OVA yesterday and tried the scripte with two Domains. It was working fine.
Then I added all my 7 domains in 7 locations. Also I changed from IP Address to Domainname.

To have only hostnames in the selection dropdown, I followed the Instructions and droped the telegraf databese.
The DB is there but there are measurements tables midding.

`> show measurements
name: measurements
name
----
cpu
disk
diskio
kernel
mem
net
processes
swap
system`

So I restarted the whole setup with the OVA and added all my domains from the Beginning. But still the tabeles are misssing.
Is there a Limit for the number of Domains?
Is it a must to user IPs for the Domain? 

The Log as on error, see below.

/usr/local/telegraf/ucs_domains_group_1.txt:

[LAN]
10.97.100.30,ucs-local\user,pwd

LOG:

`....

2021-09-22 10:16:28,362 - ERROR - Exception with print_output:
'transport'
Traceback (most recent call last):
  File "/usr/local/telegraf/ucs_traffic_monitor.py", line 2676, in main
    print_output()
  File "/usr/local/telegraf/ucs_traffic_monitor.py", line 2631, in print_output
    print_output_in_influxdb_lp()
  File "/usr/local/telegraf/ucs_traffic_monitor.py", line 2349, in print_output_in_influxdb_lp
    ',transport=' + per_fi_port_dict['transport']
KeyError: 'transport'
2021-09-22 10:16:28,363 - INFO - Pickle sessions for next time in /usr/local/telegraf/ucs_traffic_monitor_ucs_domains_group_1.pickle : {'10.97.100.30': {'sdk': <ucsmsdk.ucshandle.UcsHandle object at 0x7efd251a1198>, 'sdk_time': 1632294844, 'cli': None}, '10.97.100.40': {'sdk': <ucsmsdk.ucshandle.UcsHandle object at 0x7efd2515e6d8>, 'sdk_time': 1632294859, 'cli': None}, '10.97.100.10': {'sdk': <ucsmsdk.ucshandle.UcsHandle object at 0x7efd251665f8>, 'sdk_time': 1632294846, 'cli': None}, '10.97.100.20': {'sdk': <ucsmsdk.ucshandle.UcsHandle object at 0x7efd251660b8>, 'sdk_time': 1632294856, 'cli': None}, '10.97.100.60': {'sdk': <ucsmsdk.ucshandle.UcsHandle object at 0x7efd2516ccc0>, 'sdk_time': 1632294845, 'cli': None}, '10.97.100.70': {'sdk': <ucsmsdk.ucshandle.UcsHandle object at 0x7efd2516cac8>, 'sdk_time': 1632294844, 'cli': None}, '10.97.100.80': {'sdk': <ucsmsdk.ucshandle.UcsHandle object at 0x7efd2516ca58>, 'sdk_time': 1632294843, 'cli': None}}
2021-09-22 10:16:28,364 - INFO -
...
    |--------------------------------------------|
    |        Response time - 10.97.100.30        |
    |--------------------------------------------|
    | CLI: Login:     5.6 s  | Query:   10.09 s  |
    | SDK: Login:    0.62 s  | Query:    9.79 s  |
    | Total:    15.69 s                          |
    |--------------------------------------------|`

**Comment by ZenHub01** [comment]
It looks like, the script has problems with ucs-mini.
I removed it from the ucs_domains_group_1, now the tables exist and I can see them in the graph.

**Comment by paregupt** [comment]
Make sure you upgrade to the latest. UCS mini support is unavailable in the OVA version.
Split the domains in multiple files. 7 domains in the same file may not scale.
Many others have run into the similar issues and found the solutions. The existing issues (open and closed) can give you detailed insights.

**Comment by paregupt** [comment]
@ZenHub01 did it work?

**Comment by paregupt** [comment]
See this to scale up UTM: https://www.since2k7.com/blog/2020/02/29/cisco-ucs-monitoring-using-grafana-influxdb-telegraf-utm-installation/#comment-55
Closing this issue. Feel free to open this issue if the problem persists. For a newer problem, feel free to open a new issue.
