### ISSUE TITLE
ERROR - Exception with print_output: 'admin_state'

### ISSUE THREAD

**Issue by privaldi** [paregupt/ucs_traffic_monitor#7]
When adding two new 6454's running 4.0(4g) I came across the following issue when running the v0.3 script. 

`2020-03-19 22:25:14,305 - ERROR - Exception with print_output:
'admin_state'
Traceback (most recent call last):
  File "/usr/local/telegraf/ucs_traffic_monitor.py", line 2083, in main
    print_output()
  File "/usr/local/telegraf/ucs_traffic_monitor.py", line 2043, in print_output
    print_output_in_influxdb_lp()
  File "/usr/local/telegraf/ucs_traffic_monitor.py", line 1901, in print_output_in_influxdb_lp
    ',serial="' + per_blade_dict['serial'] + '"'
KeyError: 'admin_state'
`

Let me know if you need anymore information, I would be glad to assist/participate in this project in anyway I can.

Again Thanks!

**Comment by paregupt** [comment]
Thanks for reporting the issue. I need access to /var/log/telegraf/ucs_traffic_monitor/ucs_traffic_monitor_ucs_domains.log.

Also, try this:
1. Stop telegraf or at least stop telegraf from running ucs_traffic_monitor.py
2. Manually run the utility and output the data in dictionary format. Send the output to a file and verify it.

`python3 /usr/local/telegraf/ucs_traffic_monitor.py /usr/local/telegraf/ucs_domains.txt dict -vvv`

I can't be asking you to share the logs file in a public forum. You can reach out to me via email which is same as my GitHub id followed by at cisco

**Comment by privaldi** [comment]
let me know when would be a good time to do a webex as this is now happening on 3 of my fabrics.

`mputeBlade object at 0x7f8530699eb8>]}}
2020-03-21 16:26:35,144 - ERROR - Exception with print_output:
'admin_state'
Traceback (most recent call last):
  File "/usr/local/telegraf/ucs_traffic_monitor.py", line 2083, in main
    print_output()
  File "/usr/local/telegraf/ucs_traffic_monitor.py", line 2043, in print_output
    print_output_in_influxdb_lp()
  File "/usr/local/telegraf/ucs_traffic_monitor.py", line 1901, in print_output_in_influxdb_lp
    ',serial="' + per_blade_dict['serial'] + '"'
KeyError: 'admin_state'
`
`2020-03-21 16:04:37,023 - ERROR - Exception with update_stats_dict
`*

**Comment by paregupt** [comment]
Can you please reach out directly via email which is same as my GitHub id followed by at cisco

**Comment by paregupt** [comment]
878aefa4dfebc6176585fd89c3a22106bcb430bb
