### ISSUE TITLE
PAUSE graphs are no longer plotting - 4.2(2d)

### ISSUE THREAD

**Issue by lucgomespagseguro** [paregupt/ucs_traffic_monitor#94]
Hello @paregupt, after updating the UCS infrastructure to version 4.2(2d), all graphs related to PAUSE counters are no longer being generated. Would you help me?
All other graphs are being collected and generated normally.
![graph_pause_01](https://user-images.githubusercontent.com/100380152/218472888-a2ea29cf-f779-442b-aa78-20ad085751ae.png)
![graph_pause_02](https://user-images.githubusercontent.com/100380152/218472892-109eb2da-c393-4d8a-9fd9-62fc6420ac53.png)

**Comment by lucgomespagseguro** [comment]
`2023-02-13 10:45:00,268 - WARNING - ---------- START (version 0.52)----------
2023-02-13 10:45:00,269 - WARNING - Line not in correct input format:IP_Address,username,password
2023-02-13 10:45:00,269 - WARNING - Line not in correct input format:IP_Address,username,password
2023-02-13 10:45:00,269 - WARNING - Line not in correct input format:IP_Address,username,password
2023-02-13 10:45:00,269 - INFO - Added 10.190.51.1 to domain dict
2023-02-13 10:45:00,269 - WARNING - Line not in correct input format:IP_Address,username,password
2023-02-13 10:45:00,269 - INFO - Added 10.190.51.7 to domain dict
2023-02-13 10:45:00,269 - WARNING - Line not in correct input format:IP_Address,username,password
2023-02-13 10:45:00,269 - INFO - Added 10.190.51.10 to domain dict
2023-02-13 10:45:00,269 - WARNING - Line not in correct input format:IP_Address,username,password
2023-02-13 10:45:00,269 - INFO - Added 10.190.51.4 to domain dict
2023-02-13 10:45:00,270 - INFO - Trying to unpickle connection for 10.190.51.1
2023-02-13 10:45:00,270 - INFO - Found 10.190.51.1 in /usr/local/telegraf/ucs_traffic_monitor_ucs_domains.pickle
2023-02-13 10:45:00,404 - INFO - Trying to unpickle connection for 10.190.51.7
2023-02-13 10:45:00,405 - INFO - Found 10.190.51.7 in /usr/local/telegraf/ucs_traffic_monitor_ucs_domains.pickle
2023-02-13 10:45:00,725 - INFO - Trying to unpickle connection for 10.190.51.10
2023-02-13 10:45:00,725 - INFO - Found 10.190.51.10 in /usr/local/telegraf/ucs_traffic_monitor_ucs_domains.pickle
2023-02-13 10:45:00,853 - INFO - Trying to unpickle connection for 10.190.51.4
2023-02-13 10:45:00,853 - INFO - Found 10.190.51.4 in /usr/local/telegraf/ucs_traffic_monitor_ucs_domains.pickle
2023-02-13 10:45:00,981 - INFO - Connect and pull stats: executor_list : [['10.190.51.1', 'cli', None], ['10.190.51.1', 'sdk', <ucsmsdk.ucshandle.UcsHandle object at 0x7f1d18b70e10>], ['10.190.51.7', 'cli', None], ['10.190.51.7', 'sdk', <ucsmsdk.ucshandle.UcsHandle object at 0x7f1d18b0b0f0>], ['10.190.51.10', 'cli', None], ['10.190.51.10', 'sdk', <ucsmsdk.ucshandle.UcsHandle object at 0x7f1d18b0b198>], ['10.190.51.4', 'cli', None], ['10.190.51.4', 'sdk', <ucsmsdk.ucshandle.UcsHandle object at 0x7f1d18b0b2b0>]]
2023-02-13 10:45:00,982 - INFO - Trying to set a new cli connection for 10.190.51.1
2023-02-13 10:45:00,982 - INFO - SDK connection for 10.190.51.1. Time:1676293458, Elapsed:2442, Refresh:6822
2023-02-13 10:45:00,990 - INFO - Trying to set a new cli connection for 10.190.51.7
2023-02-13 10:45:00,991 - INFO - SDK connection for 10.190.51.7. Time:1676295437, Elapsed:463, Refresh:6594
2023-02-13 10:45:00,991 - INFO - Trying to set a new cli connection for 10.190.51.10
2023-02-13 10:45:00,992 - INFO - SDK connection for 10.190.51.10. Time:1676292981, Elapsed:2919, Refresh:6203
2023-02-13 10:45:00,993 - INFO - Trying to set a new cli connection for 10.190.51.4
2023-02-13 10:45:00,994 - INFO - SDK connection for 10.190.51.4. Time:1676295437, Elapsed:463, Refresh:6242
2023-02-13 10:45:01,229 - INFO - Query class_ids for 10.190.51.1
2023-02-13 10:45:01,404 - ERROR - ConnectHandler failed for domain 10.190.51.7. EOFError :
Traceback (most recent call last):
  File "/usr/local/telegraf/ucs_traffic_monitor.py", line 423, in set_ucs_connection
    timeout=user_args.get('conn_timeout'))
  File "/usr/local/lib/python3.6/site-packages/netmiko/ssh_dispatcher.py", line 259, in ConnectHandler
    return ConnectionClass(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/netmiko/base_connection.py", line 327, in __init__
    self._open()
  File "/usr/local/lib/python3.6/site-packages/netmiko/base_connection.py", line 332, in _open
    self.establish_connection()
  File "/usr/local/lib/python3.6/site-packages/netmiko/base_connection.py", line 901, in establish_connection
    self.remote_conn_pre.connect(**ssh_connect_params)
  File "/usr/local/lib/python3.6/site-packages/paramiko/client.py", line 406, in connect
    t.start_client(timeout=timeout)
  File "/usr/local/lib/python3.6/site-packages/paramiko/transport.py", line 660, in start_client
    raise e
  File "/usr/local/lib/python3.6/site-packages/paramiko/transport.py", line 2055, in run
    ptype, m = self.packetizer.read_message()
  File "/usr/local/lib/python3.6/site-packages/paramiko/packet.py", line 459, in read_message
    header = self.read_all(self.__block_size_in, check_rekey=True)
  File "/usr/local/lib/python3.6/site-packages/paramiko/packet.py", line 303, in read_all
    raise EOFError()
EOFError
2023-02-13 10:45:01,411 - ERROR - Exiting for 10.190.51.7 due to invalid cli_handle
`

**Comment by paregupt** [comment]
Try a manual ssh to FI from the UTM host and if it doesn't work, please resolve it.
The logs show a timeout.
Also, seems like too many domains in the same file. Consider adding one domain per input file, but this is not related to your Pause issues.
Finally, if it's sensitive, please remove IPs from your logs.

**Comment by lucgomespagseguro** [comment]
Hi @paregupt, I did a test manually logging into the UCS and it worked

"
[root@tbvmgrafana-utah-tb-cisco ucs_traffic_monitor]# ssh utm_user@xx.xxx.xxx.xxx
Cisco UCS 6300 Series Fabric Interconnect
Password:
Cisco Nexus Operating System (NX-OS) Software
TAC support: http://www.cisco.com/tac
Copyright (c) 2009, Cisco Systems, Inc. All rights reserved.
The copyrights to certain works contained in this software are
owned by other third parties and used and distributed under
license. Certain components of this software are licensed under
the GNU General Public License (GPL) version 2.0 or the GNU
Lesser General Public License (LGPL) Version 2.1. A copy of each
such license is available at
http://www.opensource.org/licenses/gpl-2.0.php and
http://www.opensource.org/licenses/lgpl-2.1.php

fi3-tb-pagpod2-A#
"

Do you need to break domains by files? Is there any other solution?

**Comment by paregupt** [comment]
Do you some other error in the logs? That may give a hint.
If not, please write to my cisco email, which is same as my GitHub id, and I can take a look.

**Comment by lucgomespagseguro** [comment]
Ok, I just sent you an email with the complete logs.

**Comment by paregupt** [comment]
For those who run into this issue, here is how we solved it.
We worked on this systems live. Seems like the netmiko library wasn't happy with opening ssh connection to the new UCSM or vice versa.

Following steps resolved the issue

1. Update Python to 3.7
2. Install UCSMSDK
3. Install netmiko
4. Edit /etc/telegraf/telegraf.conf file to use python3.7

The aim was to upgrade the netmiko library but its later version was not compatible with Python 3.6. This means, Python must be upgraded to version 3.7 or later. New version of Python requires installing ucsmsdk for it and then running the UTM collector via the new Python.

For us it look much longer because we tried installing Python 3.11, which is the latest as of today. However, Python 3.11 ran into SSL dependency on pip which prevented installation of netmiko and ucsmsdk. In general, I recommend running the latest modules, but in this case, we used the latest rebuild of Python 3.7 which did not give the SSL issues with pip and allowed to install netmiko and ucsmsdk.

Do not run these steps until you run into this issue. I am not sure if all systems will run into this issue at all. UCSM 4.2(2d).

**Comment by lucgomespagseguro** [comment]
Hi @paregupt,

I ended up needing to install the "requests" module as well, in addition to the "netmiko" and "ucsmsdk" modules:

`[root@gtvmgrafana-utah-gt-cisco Python-3.7.16]# tail -f /var/log/telegraf/telegraf.log
2023-02-27T01:34:20Z E! [inputs.exec] Error in plugin: exec: signal: terminated for command 'python3 /usr/local/telegraf/ucs_traffic_monitor.py /usr/local/telegraf/ucs_domains_group_1.txt influxdb-lp -vv':
2023-02-27T01:34:24Z I! [agent] Hang on, flushing any cached metrics before shutdown
2023-02-27T01:34:24Z I! [agent] Stopping running outputs
2023-02-27T01:34:24Z I! Loaded inputs: cpu disk diskio exec (2x) kernel mem net processes snmp (3x) swap system
2023-02-27T01:34:24Z I! Loaded aggregators:
2023-02-27T01:34:24Z I! Loaded processors: regex (3x)
2023-02-27T01:34:24Z I! Loaded outputs: influxdb
2023-02-27T01:34:24Z I! Tags enabled: host=gtvmgrafana-utah-gt-cisco
2023-02-27T01:34:24Z I! [agent] Config: Interval:10s, Quiet:false, Hostname:"gtvmgrafana-utah-gt-cisco", Flush Interval:10s
2023-02-27T01:34:30Z E! [inputs.exec] Error in plugin: exec: exit status 1 for command 'python3.7 /usr/local/telegraf/mds_traffic_monitor_high_frequency.py /usr/local/telegraf/mds_group_pagcloud.txt influxdb-lp -vv': Traceback (most recent call last):...
2023-02-27T01:35:00Z E! [inputs.exec] Error in plugin: exec: exit status 1 for command 'python3.7 /usr/local/telegraf/mds_traffic_monitor_high_frequency.py /usr/local/telegraf/mds_group_pagcloud.txt influxdb-lp -vv': Traceback (most recent call last):...

[root@gtvmgrafana-utah-gt-cisco Python-3.7.16]# python3.7 /usr/local/telegraf/mds_traffic_monitor_high_frequency.py /usr/local/telegraf/mds_group_pagcloud.txt influxdb-lp -vv
Traceback (most recent call last):
  File "/usr/local/telegraf/mds_traffic_monitor_high_frequency.py", line 17, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
`

After all it worked!
