### ISSUE TITLE
Setting up UTM for the 1st time using OVA but not working

### ISSUE THREAD

**Issue by tjalloul** [paregupt/ucs_traffic_monitor#97]
I Installed UTM using OVA and did the upgrade, but it is not working.
I have 2 domains added in 2 different txt files. The logs are in ucs_traffic_monitor_ucs_domains_group_1.log ares showing 
2024-02-02 15:41:10,358 - ERROR - UcsHandle <ucsmsdk.ucshandle.UcsHandle object at 0x7fd0780c4f60> unable to login to X.X.X.X in 10 seconds : timeout : The read operation timed out
Traceback (most recent call last):
  File "/usr/local/telegraf/ucs_traffic_monitor.py", line 428, in set_ucs_connection
    handle.login(timeout=CONNECTION_TIMEOUT)
  File "/usr/local/lib/python3.6/site-packages/ucsmsdk/ucshandle.py", line 135, in login
    return self._login(auto_refresh, force, timeout=timeout)
  File "/usr/local/lib/python3.6/site-packages/ucsmsdk/ucssession.py", line 599, in _login
    response = self.post_elem(elem, timeout=timeout)
  File "/usr/local/lib/python3.6/site-packages/ucsmsdk/ucssession.py", line 315, in post_elem
    response_str = self.post_xml(xml_str, timeout=timeout)
  File "/usr/local/lib/python3.6/site-packages/ucsmsdk/ucssession.py", line 264, in post_xml
    response_str = self.post(uri=ucsm_uri, data=xml_str, read=read, timeout=timeout)
  File "/usr/local/lib/python3.6/site-packages/ucsmsdk/ucssession.py", line 244, in post
    timeout=timeout)
  File "/usr/local/lib/python3.6/site-packages/ucsmsdk/ucsdriver.py", line 262, in post
    response = opener.open(request, timeout=timeout)
  File "/usr/lib64/python3.6/urllib/request.py", line 526, in open
    response = self._open(req, data)
  File "/usr/lib64/python3.6/urllib/request.py", line 544, in _open
    '_open', req)
  File "/usr/lib64/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python3.6/site-packages/ucsmsdk/ucsdriver.py", line 55, in https_open
    return self.do_open(TLSConnection, req)
  File "/usr/lib64/python3.6/urllib/request.py", line 1352, in do_open
    r = h.getresponse()
  File "/usr/lib64/python3.6/http/client.py", line 1346, in getresponse
    response.begin()
  File "/usr/lib64/python3.6/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/usr/lib64/python3.6/http/client.py", line 268, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib64/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib64/python3.6/ssl.py", line 1005, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib64/python3.6/ssl.py", line 867, in read
    return self._sslobj.read(len, buffer)
  File "/usr/lib64/python3.6/ssl.py", line 590, in read
    v = self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out
2024-02-02 15:41:10,362 - ERROR - Exiting for X.X.X.X due to invalid sdk_handle
I did the Verification using Python UCSM SDK (https://www.since2k7.com/blog/2020/02/29/cisco-ucs-monitoring-using-grafana-influxdb-telegraf-utm-installation/#Verification_using_Python_UCSM_SDK) and it is working

**Comment by tjalloul** [comment]
Hello, the connectivity using the ucsmsdk was tested and here is the result:
$ python3.6
>>> from ucsmsdk.ucshandle import UcsHandle
>>> handle = UcsHandle('X.X.X.X','xxxx','xxxx')
>>> handle.login()
True
>>> obj = handle.query_classid(class_id='adaptorVnicStats')
>>> print(obj)
[<ucsmsdk.mometa.adaptor.AdaptorVnicStats.AdaptorVnicStats object at 0x7fe613d2f898>, <ucsmsdk.mometa.adaptor.AdaptorVnicStats.AdaptorVnicStats object at 0x7fe613d2f400>, <ucsmsdk.mometa.adt 0x7fe613d30b70>, <ucsmsdk.mometa.adaptor.AdaptorVnicStats.AdaptorVnicStats object at 0x7fe613d302b0>, <ucsmsdk.mometa.adaptor.AdaptorVnicStats.AdaptorVnicStats object at 0x7fe613d30f98>, VnicStats object at 0x7fe613d31400>, <ucsmsdk.mometa.adaptor.AdaptorVnicStats.AdaptorVnicStats object at 0x7fe613d31898>, <ucsmsdk.mometa.adaptor.AdaptorVnicStats.AdaptorVnicStats object atrVnicStats.AdaptorVnicStats object at 0x7fe613d32208>, <ucsmsdk.mometa.adaptor.AdaptorVnicStats.AdaptorVnicStats object at 0x7fe613d329b0>, <ucsmsdk.mometa.adaptor.AdaptorVnicStats.AdaptorVeta.adaptor.AdaptorVnicStats.AdaptorVnicStats object at 0x7fe613d326a0>, <ucsmsdk.mometa.adaptor.AdaptorVnicStats.AdaptorVnicStats object at 0x7fe613d36240>, <ucsmsdk.mometa.adaptor.Adaptor6d8>, <ucsmsdk.mometa.adaptor.AdaptorVnicStats.AdaptorVnicStats object at 0x7fe613d2ea90>, <ucsmsdk.mometa.adaptor.AdaptorVnicStats.AdaptorVnicStats object at 0x7fe613cc3908>, <ucsmsdk.momeect at 0x7fe613c40240>, <ucsmsdk.mometa.adaptor.AdaptorVnicStats.AdaptorVnicStats object at 0x7fe613c40278>, <ucsmsdk.mometa.adaptor.AdaptorVnicStats.AdaptorVnicStats object at 0x7fe613c402aptorVnicStats object at 0x7fe613c402e8>, <ucsmsdk.mometa.adaptor.AdaptorVnicStats.AdaptorVnicStats object at 0x7fe613c40320>, <ucsmsdk.mometa.adaptor.AdaptorVnicStats.AdaptorVnicStats objedaptorVnicStats.AdaptorVnicStats object at 0x7fe613c40390>, <ucsmsdk.mometa.adaptor.AdaptorVnicStats.AdaptorVnicStats object at 0x7fe613c403c8>, <ucsmsdk.mometa.adaptor.AdaptorVnicStats.Adak.mometa.adaptor.AdaptorVnicStats.AdaptorVnicStats object at 0x7fe613c40438>, <ucsmsdk.mometa.adaptor.AdaptorVnicStats.AdaptorVnicStats object at 0x7fe613c40470>, <ucsmsdk.mometa.adaptor.Ad13c404a8>, <ucsmsdk.mometa.adaptor.AdaptorVnicStats.AdaptorVnicStats object at 0x7fe613c404e0>, <ucsmsdk.mometa.adaptor.AdaptorVnicStats.AdaptorVnicStats object at 0x7fe613c40518>, <ucsmsdks object at 0x7fe613c40550>, <ucsmsdk.mometa.adaptor.AdaptorVnicStats.AdaptorVnicStats object at 0x7fe613c40588>, <ucsmsdk.mometa.adaptor.AdaptorVnicStats.AdaptorVnicStats object at 0x7fe61ts.AdaptorVnicStats object at 0x7fe613c405f8>, <ucsmsdk.mometa.adaptor.AdaptorVnicStats.AdaptorVnicStats object at 0x7fe613c40630>, <ucsmsdk.mometa.adaptor.AdaptorVnicStats.AdaptorVnicStatstor.AdaptorVnicStats.AdaptorVnicStats object at 0x7fe613c406a0>, <ucsmsdk.mometa.adaptor.AdaptorVnicStats.AdaptorVnicStats object at 0x7fe613c406d8>, <ucsmsdk.mometa.adaptor.AdaptorVnicStatcsmsdk.mometa.adaptor.AdaptorVnicStats.AdaptorVnicStats object at 0x7fe613c40748>, <ucsmsdk.mometa.adaptor.AdaptorVnicStats.AdaptorVnicStats object at 0x7fe613c40780>, <ucsmsdk.mometa.adaptx7fe613c407b8>, <ucsmsdk.mometa.adaptor.AdaptorVnicStats.AdaptorVnicStats object at 0x7fe613c407f0>, <ucsmsdk.mometa.adaptor.AdaptorVnicStats.AdaptorVnicStats object at 0x7fe613cc0358>, <uccStats object at 0x7fe613d36b70>, <ucsmsdk.mometa.adaptor.AdaptorVnicStats.AdaptorVnicStats object at 0x7fe613cba710>, <ucsmsdk.mometa.adaptor.AdaptorVnicStats.AdaptorVnicStats object at 0xicStats.AdaptorVnicStats object at 0x7fe613cbaba8>, <ucsmsdk.mometa.adaptor.AdaptorVnicStats.AdaptorVnicStats object at 0x7fe613d38048>, <ucsmsdk.mometa.adaptor.AdaptorVnicStats.AdaptorVnic.adaptor.AdaptorVnicStats.AdaptorVnicStats object at 0x7fe613d38e80>, <ucsmsdk.mometa.adaptor.AdaptorVnicStats.AdaptorVnicStats object at 0x7fe613d38a20>, <ucsmsdk.mometa.adaptor.AdaptorVni>, <ucsmsdk.mometa.adaptor.AdaptorVnicStats.AdaptorVnicStats object at 0x7fe613cbbdd8>, <ucsmsdk.mometa.adaptor.AdaptorVnicStats.AdaptorVnicStats object at 0x7fe613cbb9b0>, <ucsmsdk.mometa. at 0x7fe613cbb518>, <ucsmsdk.mometa.adaptor.AdaptorVnicStats.AdaptorVnicStats object at 0x7fe613cbc240>, <ucsmsdk.mometa.adaptor.AdaptorVnicStats.AdaptorVnicStats object at 0x7fe613cbc550>orVnicStats object at 0x7fe613cbc7b8>, <ucsmsdk.mometa.adaptor.AdaptorVnicStats.AdaptorVnicStats object at 0x7fe613cbcc18>, <ucsmsdk.mometa.adaptor.AdaptorVnicStats.AdaptorVnicStats object torVnicStats.AdaptorVnicStats object at 0x7fe613cbee80>, <ucsmsdk.mometa.adaptor.AdaptorVnicStats.AdaptorVnicStats object at 0x7fe613cbe9e8>, <ucsmsdk.mometa.adaptor.AdaptorVnicStats.Adaptoometa.adaptor.AdaptorVnicStats.AdaptorVnicStats object at 0x7fe613cbe0b8>, <ucsmsdk.mometa.adaptor.AdaptorVnicStats.AdaptorVnicStats object at 0x7fe613c40828>, <ucsmsdk.mometa.adaptor.Adapt40860>, <ucsmsdk.mometa.adaptor.AdaptorVnicStats.AdaptorVnicStats object at 0x7fe613c40898>, <ucsmsdk.mometa.adaptor.AdaptorVnicStats.AdaptorVnicStats object at 0x7fe613c408d0>, <ucsmsdk.mobject at 0x7fe613c40908>, <ucsmsdk.mometa.adaptor.AdaptorVnicStats.AdaptorVnicStats object at 0x7fe613c40940>, <ucsmsdk.mometa.adaptor.AdaptorVnicStats.AdaptorVnicStats object at 0x7fe613c4AdaptorVnicStats object at 0x7fe613c409b0>, <ucsmsdk.mometa.adaptor.AdaptorVnicStats.AdaptorVnicStats object at 0x7fe613c409e8>, <ucsmsdk.mometa.adaptor.AdaptorVnicStats.AdaptorVnicStats ob.AdaptorVnicStats.AdaptorVnicStats object at 0x7fe613c40a58>, <ucsmsdk.mometa.adaptor.AdaptorVnicStats.AdaptorVnicStats object at 0x7fe613c40a90>, <ucsmsdk.mometa.adaptor.AdaptorVnicStats.Asdk.mometa.adaptor.AdaptorVnicStats.AdaptorVnicStats object at 0x7fe613c40b00>, <ucsmsdk.mometa.adaptor.AdaptorVnicStats.AdaptorVnicStats object at 0x7fe613c40b38>, <ucsmsdk.mometa.adaptor.e613c40b70>, <ucsmsdk.mometa.adaptor.AdaptorVnicStats.AdaptorVnicStats object at 0x7fe613c40ba8>, <ucsmsdk.mometa.adaptor.AdaptorVnicStats.AdaptorVnicStats object at 0x7fe613c40be0>, <ucsmsats object at 0x7fe613c40c18>, <ucsmsdk.mometa.adaptor.AdaptorVnicStats.AdaptorVnicStats object at 0x7fe613c40c50>, <ucsmsdk.mometa.adaptor.AdaptorVnicStats.AdaptorVnicStats object at 0x7fetats.AdaptorVnicStats object at 0x7fe613c40cc0>, <ucsmsdk.mometa.adaptor.AdaptorVnicStats.AdaptorVnicStats object at 0x7fe613c40cf8>, <ucsmsdk.mometa.adaptor.AdaptorVnicStats.AdaptorVnicStaaptor.AdaptorVnicStats.AdaptorVnicStats object at 0x7fe613c40d68>, <ucsmsdk.mometa.adaptor.AdaptorVnicStats.AdaptorVnicStats object at 0x7fe613c40da0>, <ucsmsdk.mometa.adaptor.AdaptorVnicSt<ucsmsdk.mometa.adaptor.AdaptorVnicStats.AdaptorVnicStats object at 0x7fe613c40e10>, <ucsmsdk.mometa.adaptor.AdaptorVnicStats.AdaptorVnicStats object at 0x7fe613c40e48>, <ucsmsdk.mometa.ada 0x7fe613c40e80>, <ucsmsdk.mometa.adaptor.AdaptorVnicStats.AdaptorVnicStats object at 0x7fe613c40eb8>, <ucsmsdk.mometa.adaptor.AdaptorVnicStats.AdaptorVnicStats object at 0x7fe613c40ef0>, <nicStats object at 0x7fe613c40f28>, <ucsmsdk.mometa.adaptor.AdaptorVnicStats.AdaptorVnicStats object at 0x7fe613c40f60>, <ucsmsdk.mometa.adaptor.AdaptorVnicStats.AdaptorVnicStats object at VnicStats.AdaptorVnicStats object at 0x7fe613c40fd0>, <ucsmsdk.mometa.adaptor.AdaptorVnicStats.AdaptorVnicStats object at 0x7fe613c51048>, <ucsmsdk.mometa.adaptor.AdaptorVnicStats.AdaptorVnta.adaptor.AdaptorVnicStats.AdaptorVnicStats object at 0x7fe613c510b8>, <ucsmsdk.mometa.adaptor.AdaptorVnicStats.AdaptorVnicStats object at 0x7fe613c510f0>, <ucsmsdk.mometa.adaptor.AdaptorV28>, <ucsmsdk.mometa.adaptor.AdaptorVnicStats.AdaptorVnicStats object at 0x7fe613c51160>, <ucsmsdk.mometa.adaptor.AdaptorVnicStats.AdaptorVnicStats object at 0x7fe613c51198>, <ucsmsdk.mometct at 0x7fe613c511d0>, <ucsmsdk.mometa.adaptor.AdaptorVnicStats.AdaptorVnicStats object at 0x7fe613c51208>, <ucsmsdk.mometa.adaptor.AdaptorVnicStats.AdaptorVnicStats object at 0x7fe613c5124ptorVnicStats object at 0x7fe613c51278>, <ucsmsdk.mometa.adaptor.AdaptorVnicStats.AdaptorVnicStats object at 0x7fe613c512b0>, <ucsmsdk.mometa.adaptor.AdaptorVnicStats.AdaptorVnicStats objecaptorVnicStats.AdaptorVnicStats object at 0x7fe613c51320>, <ucsmsdk.mometa.adaptor.AdaptorVnicStats.AdaptorVnicStats object at 0x7fe613c51358>, <ucsmsdk.mometa.adaptor.AdaptorVnicStats.Adap.mometa.adaptor.AdaptorVnicStats.AdaptorVnicStats object at 0x7fe613c513c8>, <ucsmsdk.mometa.adaptor.AdaptorVnicStats.AdaptorVnicStats object at 0x7fe613c51400>, <ucsmsdk.mometa.adaptor.Ada3c51438>, <ucsmsdk.mometa.adaptor.AdaptorVnicStats.AdaptorVnicStats object at 0x7fe613c51470>, <ucsmsdk.mometa.adaptor.AdaptorVnicStats.AdaptorVnicStats object at 0x7fe613c514a8>, <ucsmsdk. object at 0x7fe613c514e0>, <ucsmsdk.mometa.adaptor.AdaptorVnicStats.AdaptorVnicStats object at 0x7fe613c51518>, <ucsmsdk.mometa.adaptor.AdaptorVnicStats.AdaptorVnicStats object at 0x7fe613s.AdaptorVnicStats object at 0x7fe613c51588>, <ucsmsdk.mometa.adaptor.AdaptorVnicStats.AdaptorVnicStats object at 0x7fe613c515c0>, <ucsmsdk.mometa.adaptor.AdaptorVnicStats.AdaptorVnicStats or.AdaptorVnicStats.AdaptorVnicStats object at 0x7fe613c51630>, <ucsmsdk.mometa.adaptor.AdaptorVnicStats.AdaptorVnicStats object at 0x7fe613c51668>, <ucsmsdk.mometa.adaptor.AdaptorVnicStatssmsdk.mometa.adaptor.AdaptorVnicStats.AdaptorVnicStats object at 0x7fe613c516d8>, <ucsmsdk.mometa.adaptor.AdaptorVnicStats.AdaptorVnicStats object at 0x7fe613c51710>, <ucsmsdk.mometa.adapto7fe613c51748>, <ucsmsdk.mometa.adaptor.AdaptorVnicStats.AdaptorVnicStats object at 0x7fe613c51780>, <ucsmsdk.mometa.adaptor.AdaptorVnicStats.AdaptorVnicStats object at 0x7fe613c517b8>, <ucsStats object at 0x7fe613c517f0>, <ucsmsdk.mometa.adaptor.AdaptorVnicStats.AdaptorVnicStats object at 0x7fe613c51828>, <ucsmsdk.mometa.adaptor.AdaptorVnicStats.AdaptorVnicStats object at 0x7cStats.AdaptorVnicStats object at 0x7fe613c51898>, <ucsmsdk.mometa.adaptor.AdaptorVnicStats.AdaptorVnicStats object at 0x7fe613c518d0>, <ucsmsdk.mometa.adaptor.AdaptorVnicStats.AdaptorVnicSadaptor.AdaptorVnicStats.AdaptorVnicStats object at 0x7fe613c51940>, <ucsmsdk.mometa.adaptor.AdaptorVnicStats.AdaptorVnicStats object at 0x7fe613c51978>, <ucsmsdk.mometa.adaptor.AdaptorVnic, <ucsmsdk.mometa.adaptor.AdaptorVnicStats.AdaptorVnicStats object at 0x7fe613c519e8>, <ucsmsdk.mometa.adaptor.AdaptorVnicStats.AdaptorVnicStats object at 0x7fe613c51a20>, <ucsmsdk.mometa.aat 0x7fe613c51a58>, <ucsmsdk.mometa.adaptor.AdaptorVnicStats.AdaptorVnicStats object at 0x7fe613c51a90>, <ucsmsdk.mometa.adaptor.AdaptorVnicStats.AdaptorVnicStats object at 0x7fe613c51ac8>,rVnicStats object at 0x7fe613c51b00>, <ucsmsdk.mometa.adaptor.AdaptorVnicStats.AdaptorVnicStats object at 0x7fe613c51b38>, <ucsmsdk.mometa.adaptor.AdaptorVnicStats.AdaptorVnicStats object aorVnicStats.AdaptorVnicStats object at 0x7fe613c51ba8>, <ucsmsdk.mometa.adaptor.AdaptorVnicStats.AdaptorVnicStats object at 0x7fe613c51be0>, <ucsmsdk.mometa.adaptor.AdaptorVnicStats.Adaptormeta.adaptor.AdaptorVnicStats.AdaptorVnicStats object at 0x7fe613c51c50>, <ucsmsdk.mometa.adaptor.AdaptorVnicStats.AdaptorVnicStats object at 0x7fe613c51c88>, <ucsmsdk.mometa.adaptor.Adapto1cc0>, <ucsmsdk.mometa.adaptor.AdaptorVnicStats.AdaptorVnicStats object at 0x7fe613c51cf8>, <ucsmsdk.mometa.adaptor.AdaptorVnicStats.AdaptorVnicStats object at 0x7fe613c51d30>, <ucsmsdk.momject at 0x7fe613c51d68>, <ucsmsdk.mometa.adaptor.AdaptorVnicStats.AdaptorVnicStats object at 0x7fe613c51da0>, <ucsmsdk.mometa.adaptor.AdaptorVnicStats.AdaptorVnicStats object at 0x7fe613c51daptorVnicStats object at 0x7fe613c51e10>, <ucsmsdk.mometa.adaptor.AdaptorVnicStats.AdaptorVnicStats object at 0x7fe613c51e48>, <ucsmsdk.mometa.adaptor.AdaptorVnicStats.AdaptorVnicStats objAdaptorVnicStats.AdaptorVnicStats object at 0x7fe613c51eb8>, <ucsmsdk.mometa.adaptor.AdaptorVnicStats.AdaptorVnicStats object at 0x7fe613c51ef0>, <ucsmsdk.mometa.adaptor.AdaptorVnicStats.Addk.mometa.adaptor.AdaptorVnicStats.AdaptorVnicStats object at 0x7fe613c51f60>, <ucsmsdk.mometa.adaptor.AdaptorVnicStats.AdaptorVnicStats object at 0x7fe613c51f98>, <ucsmsdk.mometa.adaptor.A613c51fd0>, <ucsmsdk.mometa.adaptor.AdaptorVnicStats.AdaptorVnicStats object at 0x7fe613c5d048>, <ucsmsdk.mometa.adaptor.AdaptorVnicStats.AdaptorVnicStats object at 0x7fe613c5d080>, <ucsmsdts object at 0x7fe613c5d0b8>, <ucsmsdk.mometa.adaptor.AdaptorVnicStats.AdaptorVnicStats object at 0x7fe613c5d0f0>, <ucsmsdk.mometa.adaptor.AdaptorVnicStats.AdaptorVnicStats object at 0x7fe6ats.AdaptorVnicStats object at 0x7fe613c5d160>, <ucsmsdk.mometa.adaptor.AdaptorVnicStats.AdaptorVnicStats object at 0x7fe613c5d198>, <ucsmsdk.mometa.adaptor.AdaptorVnicStats.AdaptorVnicStatptor.AdaptorVnicStats.AdaptorVnicStats object at 0x7fe613c5d208>, <ucsmsdk.mometa.adaptor.AdaptorVnicStats.AdaptorVnicStats object at 0x7fe613c5d240>, <ucsmsdk.mometa.adaptor.AdaptorVnicStaucsmsdk.mometa.adaptor.AdaptorVnicStats.AdaptorVnicStats object at 0x7fe613c5d2b0>, <ucsmsdk.mometa.adaptor.AdaptorVnicStats.AdaptorVnicStats object at 0x7fe613c5d2e8>, <ucsmsdk.mometa.adap0x7fe613c5d320>, <ucsmsdk.mometa.adaptor.AdaptorVnicStats.AdaptorVnicStats object at 0x7fe613c5d358>, <ucsmsdk.mometa.adaptor.AdaptorVnicStats.AdaptorVnicStats object at 0x7fe613c5d390>, <uicStats object at 0x7fe613c5d3c8>, <ucsmsdk.mometa.adaptor.AdaptorVnicStats.AdaptorVnicStats object at 0x7fe613c5d400>, <ucsmsdk.mometa.adaptor.AdaptorVnicStats.AdaptorVnicStats object at 0nicStats.AdaptorVnicStats object at 0x7fe613c5d470>, <ucsmsdk.mometa.adaptor.AdaptorVnicStats.AdaptorVnicStats object at 0x7fe613c5d4a8>, <ucsmsdk.mometa.adaptor.AdaptorVnicStats.AdaptorVnia.adaptor.AdaptorVnicStats.AdaptorVnicStats object at 0x7fe613c5d518>, <ucsmsdk.mometa.adaptor.AdaptorVnicStats.AdaptorVnicStats object at 0x7fe613c5d550>, <ucsmsdk.mometa.adaptor.AdaptorVn8>, <ucsmsdk.mometa.adaptor.AdaptorVnicStats.AdaptorVnicStats object at 0x7fe613c5d5c0>, <ucsmsdk.mometa.adaptor.AdaptorVnicStats.AdaptorVnicStats object at 0x7fe613c5d5f8>, <ucsmsdk.mometat at 0x7fe613c5d630>, <ucsmsdk.mometa.adaptor.AdaptorVnicStats.AdaptorVnicStats object at 0x7fe613c5d668>, <ucsmsdk.mometa.adaptor.AdaptorVnicStats.AdaptorVnicStats object at 0x7fe613c5d6a0torVnicStats object at 0x7fe613c5d6d8>, <ucsmsdk.mometa.adaptor.AdaptorVnicStats.AdaptorVnicStats object at 0x7fe613c5d710>, <ucsmsdk.mometa.adaptor.AdaptorVnicStats.AdaptorVnicStats objectptorVnicStats.AdaptorVnicStats object at 0x7fe613c5d780>, <ucsmsdk.mometa.adaptor.AdaptorVnicStats.AdaptorVnicStats object at 0x7fe613c5d7b8>, <ucsmsdk.mometa.adaptor.AdaptorVnicStats.Adaptmometa.adaptor.AdaptorVnicStats.AdaptorVnicStats object at 0x7fe613c5d828>, <ucsmsdk.mometa.adaptor.AdaptorVnicStats.AdaptorVnicStats object at 0x7fe613c5d860>, <ucsmsdk.mometa.adaptor.Adapc5d898>, <ucsmsdk.mometa.adaptor.AdaptorVnicStats.AdaptorVnicStats object at 0x7fe613c5d8d0>, <ucsmsdk.mometa.adaptor.AdaptorVnicStats.AdaptorVnicStats object at 0x7fe613c5d908>, <ucsmsdk.mobject at 0x7fe613c5d940>, <ucsmsdk.mometa.adaptor.AdaptorVnicStats.AdaptorVnicStats object at 0x7fe613c5d978>, <ucsmsdk.mometa.adaptor.AdaptorVnicStats.AdaptorVnicStats object at 0x7fe613c.AdaptorVnicStats object at 0x7fe613c5d9e8>, <ucsmsdk.mometa.adaptor.AdaptorVnicStats.AdaptorVnicStats object at 0x7fe613c5da20>, <ucsmsdk.mometa.adaptor.AdaptorVnicStats.AdaptorVnicStats or.AdaptorVnicStats.AdaptorVnicStats object at 0x7fe613c5da90>, <ucsmsdk.mometa.adaptor.AdaptorVnicStats.AdaptorVnicStats object at 0x7fe613c5dac8>, <ucsmsdk.mometa.adaptor.AdaptorVnicStats.msdk.mometa.adaptor.AdaptorVnicStats.AdaptorVnicStats object at 0x7fe613c5db38>]
>>> handle.logout()
True

**Comment by tjalloul** [comment]
Issue was related to the local account taking too long to connect while using radius server as primary authentication

**Comment by tjalloul** [comment]
Issue fixed
